# Generated by Django 3.2.5 on 2021-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productdescription', models.TextField(max_length=500)),
                ('prodcutprice', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
